language: node_js
node_js:
  - 'node'
  - '7'

branches:
  only:
    - 'master'

matrix:
  fast_finish: true

install:
  - npm install
  - npm link

script:
  - npm test
  - mkdir travis
  - cd travis
  - bs init
  - bs export
  - bs pdf --verbose
  